changes in ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -36,7 +36,13 @@ jobs:
 
       - name: Check target directory for JAR
         run: |
-          ls -l MicroService-webClient-docker/${{ matrix.service }}/target
+          TARGET_DIR=MicroService-webClient-docker/${{ matrix.service }}/target
+          if [ -d "$TARGET_DIR" ]; then
+            ls -l $TARGET_DIR
+          else
+            echo "Error: Target directory not found or no JAR file generated."
+            exit 1
+          fi
 
   docker-login:
     runs-on: ubuntu-latest
@@ -59,17 +65,17 @@ jobs:
           sudo apt-get install -y docker-compose
 
       - name: Run Docker Compose (staging)
-        #        if: github.ref == 'refs/heads/staging'
+        if: github.ref == 'refs/heads/staging'
         run: |
           cd MicroService-webClient-docker
-          docker-compose down -v
+          docker-compose down -v || true
           docker-compose up --build -d
           cd ../..
 
       - name: Run Docker Compose (main)
-        #        if: github.ref == 'refs/heads/main'
+        if: github.ref == 'refs/heads/main'
         run: |
           cd MicroService-webClient-docker
-          docker-compose down -v
+          docker-compose down -v || true
           docker-compose up --build -d
           cd ../..
